[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='8245d9f3721598b3d950705394c00e0f81081ac3e0ad9ad262537468675d8f34'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
